# Generated by Django 4.1.5 on 2023-01-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=256, unique=True),
        ),
    ]
